github: [NMarkgraf]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: NormanMarkgraf # Replace with a single Patreon username
ko_fi: benorman # Replace with a single Ko-fi username
liberapay: nmarkgraf # Replace with a single Liberapay username
buy_me_a_coffee: norman.markgraf
